"updates":
- "directory": "/"
  "groups":
    "all":
      "patterns":
      - "*"
  "open-pull-request-limit": 10
  "package-ecosystem": "cargo"
  "schedule":
    "interval": "daily"
    "time": "04:00"
- "directory": "/"
  "groups":
    "all":
      "patterns":
      - "*"
  "open-pull-request-limit": 10
  "package-ecosystem": "github-actions"
  "schedule":
    "interval": "daily"
    "time": "04:00"
"version": 2
