name: "CI/nix"
on:
  workflow_call:

jobs:
  flake_build:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: cachix/install-nix-action@v22
      - run: nix build --no-link path:.#

  flake_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: cachix/install-nix-action@v22
      - run: nix flake check path:.
