name: "nix-update"
on:
  workflow_dispatch:
  schedule:
    - cron: "32 19 * * 0"

jobs:
  flake_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: cachix/install-nix-action@v22
      - run: nix flake update
      - run: nix flake check .
      - run: nix build --no-link .#

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: "Update flake.lock"
          assignees: antifuchs
          delete-branch: true
          branch: flake-update
          base: main
          title: "Update flake.lock"
